version: "3.3"
services:
  # Go-Web main container
  go_web:
    container_name: go-web
    build:
      context: .
      dockerfile: Dockerfile
    image: ikdev/go-web
    restart: unless-stopped
    tty: true
    working_dir: /app
    volumes:
      - ./config.yml:/app/config.yml
    ports:
      - "8009:8005"
    networks:
      - goweb
  # MySQL container
  go_web_mysql:
    container_name: "go_web_mysql"
    image: "mysql:5.7.28"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - goweb
  # Redis container
  go_web_redis:
    container_name: "redis_queue"
    image: "redis:latest"
    ports:
      - "6379:6379"
    networks:
      - goweb
  # MongoDB container
  go_web_mongo:
    container_name: "mongo"
    image: "mongo"
    environment:
      - MONGO_INITDB_DATABASE={MONGO_DATABASE}
    ports:
      - "27017:27017"
    networks:
      - goweb
  # Elasticsearch container
  go_web_elastic:
    container_name: "elastic"
    image: "elasticsearch:7.5.1"
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
    networks:
      - goweb
networks:
  goweb:
volumes:
  mysql: