version: "3.3"
services:
  go_web:
    container_name: "go_web"
    image: "mysql:5.7.28"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - "3308:3306"
  go_web_redis:
    container_name: "redis_queue"
    image: "redis:latest"
    ports:
      - "6379:6379"
  go_web_mongo:
    container_name: "mongo"
    image: "mongo"
    environment:
      - MONGO_INITDB_DATABASE={MONGO_DATABASE}
    ports:
      - "27017:27017"
  go_web_elastic:
    container_name: "elastic"
    image: "elasticsearch:7.5.1"
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"