#Define single routes
routes:
  home:
    path: "/"
    action: "Main"
    method: "GET"
    #middleware:""
  users:
    path: "/users"
    action: "NewUser"
    method: "POST"
    #middleware:""
  login:
    path: "/login"
    action: "Login"
    method: "POST"
    #middleware:""
#Define groups of routes
groups:
  admin:
    prefix: "/admin"
    routes:
      test:
        path: "/test"
        action: "TestUser"
        method: "GET"
    middleware:
      - RefreshToken
      - Auth