routes:
  home:
    path: "/"
    action: "HomeAction" # Bind controller@method instead of single action
    method: "GET" # Default method
    #middleware:
  users:
    path: "/users"
    action: "NewUser"
    mathod: "POST"
    #middleware
  login:
    path: "/login"
    action: "Login"
    method: "POST"
    #middleware: "Auth"
groups:
  admin:
    prefix: "/admin"
    routes:
      test:
        path: "/test"
        action: "TestUser"
        method: "GET" # default method
        #middleware:
    middleware:
      - RefreshToken
      - Auth
## NOT WORKING - JUST FOR EXAMPLE