routes:
  home:
    path: "/"
    action: "Main" # Bind controller@method instead of single action
    method: "GET"
  users:
    path: "/users"
    action: "NewUser"
    method: "POST"
  login:
    path: "/login"
    action: "Login"
    method: "POST"
groups:
  admin:
    prefix: "/admin"
    routes:
      test:
        path: "/test"
        action: "TestUser"
        method: "GET"
    middleware:
      - RefreshToken
      - Auth