routes:
  home:
    path: "/"
    action: "HomeAction" # Bind controller@method instead of single action
    method: "GET" # Default method
    #middleware:
  users:
    path: "/users"
    action: "NewUserAction"
    mathod: "POST"
    #middleware:
  login:
    path: "/login"
    action: "LoginAction"
    method: "POST"
    #middleware:
groups:
  admin:
    prefix: "/admin"
    routes:
      test:
        path: "/test"
        action: "TestUserAction"
        method: "GET" # default method
      #middleware:
  #middleware:
  #  - RefreshTokenMiddleware
  #  - AuthMiddleware

## NOT WORKING - JUST FOR EXAMPLE