#Define single routes
routes:
  home:
    path: "/"
    action: "HomeController@Main"
    method: "GET"
    middleware:
      - RateLimiter
      - Logging
  users:
    path: "/users"
    action: "UserController@Insert"
    method: "POST"
    #middleware:""
  login:
    path: "/login"
    action: "AuthController@Login"
    method: "POST"
    middleware:
      - Logging
#Define groups of routes
groups:
  admin:
    prefix: "/admin"
    routes:
      test:
        path: "/test"
        action: "UserController@Profile"
        method: "GET"
        middleware:
          - Logging
          - RateLimiter
    middleware:
      - RefreshToken
      - Auth